<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="11" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="682256" started-at="2021-03-28T20:23:38 CAT" finished-at="2021-03-28T20:35:00 CAT">
    <groups>
    </groups>
    <test name="Test" duration-ms="682256" started-at="2021-03-28T20:23:38 CAT" finished-at="2021-03-28T20:35:00 CAT">
      <class name="ReactJsSanityTest.TC08_SearchTest">
        <test-method status="PASS" signature="searchUat()[pri:10, instance:ReactJsSanityTest.TC08_SearchTest@17046283]" name="searchUat" duration-ms="62154" started-at="2021-03-28T20:26:51 CAT" finished-at="2021-03-28T20:27:53 CAT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchUat -->
      </class> <!-- ReactJsSanityTest.TC08_SearchTest -->
      <class name="ReactJsSanityTest.TC01_LoginTest">
        <test-method status="PASS" signature="loginUat()[pri:0, instance:ReactJsSanityTest.TC01_LoginTest@29626d54]" name="loginUat" duration-ms="42098" started-at="2021-03-28T20:29:35 CAT" finished-at="2021-03-28T20:30:17 CAT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUat -->
      </class> <!-- ReactJsSanityTest.TC01_LoginTest -->
      <class name="ReactJsSanityTest.TC06_FurnitureAddItemToBagTest">
        <test-method status="PASS" signature="furnitureFlow()[pri:6, instance:ReactJsSanityTest.TC06_FurnitureAddItemToBagTest@5bd03f44]" name="furnitureFlow" duration-ms="37469" started-at="2021-03-28T20:27:53 CAT" finished-at="2021-03-28T20:28:31 CAT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- furnitureFlow -->
        <test-method status="PASS" signature="addItemToBag()[pri:7, instance:ReactJsSanityTest.TC06_FurnitureAddItemToBagTest@5bd03f44]" name="addItemToBag" duration-ms="63816" started-at="2021-03-28T20:28:31 CAT" finished-at="2021-03-28T20:29:35 CAT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addItemToBag -->
      </class> <!-- ReactJsSanityTest.TC06_FurnitureAddItemToBagTest -->
      <class name="ReactJsSanityTest.TC04_RegisterNewOnlineProfileTest">
        <test-method status="PASS" signature="registerNewOnline()[pri:4, instance:ReactJsSanityTest.TC04_RegisterNewOnlineProfileTest@5a63f509]" name="registerNewOnline" duration-ms="55890" started-at="2021-03-28T20:30:17 CAT" finished-at="2021-03-28T20:31:13 CAT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerNewOnline -->
      </class> <!-- ReactJsSanityTest.TC04_RegisterNewOnlineProfileTest -->
      <class name="ReactJsSanityTest.TC02_LogOutTest">
        <test-method status="PASS" signature="launchReactUat()[pri:1, instance:ReactJsSanityTest.TC02_LogOutTest@70e8f8e]" name="launchReactUat" duration-ms="43865" started-at="2021-03-28T20:25:36 CAT" finished-at="2021-03-28T20:26:20 CAT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchReactUat -->
        <test-method status="PASS" signature="logOutUat()[pri:2, instance:ReactJsSanityTest.TC02_LogOutTest@70e8f8e]" name="logOutUat" duration-ms="31490" started-at="2021-03-28T20:26:20 CAT" finished-at="2021-03-28T20:26:51 CAT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutUat -->
      </class> <!-- ReactJsSanityTest.TC02_LogOutTest -->
      <class name="ReactJsSanityTest.TC05_TodaysDealTest">
        <test-method status="FAIL" signature="todaysDeal()[pri:5, instance:ReactJsSanityTest.TC05_TodaysDealTest@2e4b8173]" name="todaysDeal" duration-ms="117732" started-at="2021-03-28T20:23:38 CAT" finished-at="2021-03-28T20:25:36 CAT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Today's Deal Sort Price High to Low or Low to High not updating Test Failed expected [R 499.00] but found [R 249.00]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Today's Deal Sort Price High to Low or Low to High not updating Test Failed expected [R 499.00] but found [R 249.00]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at ReactJsSanityTest.TC05_TodaysDealTest.todaysDeal(TC05_TodaysDealTest.java:202)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- todaysDeal -->
      </class> <!-- ReactJsSanityTest.TC05_TodaysDealTest -->
      <class name="ReactJsSanityTest.TC07_FurnitureCollectFromStoreTest">
        <test-method status="PASS" signature="launchApplication()[pri:8, instance:ReactJsSanityTest.TC07_FurnitureCollectFromStoreTest@6e4784bc]" name="launchApplication" duration-ms="32602" started-at="2021-03-28T20:31:13 CAT" finished-at="2021-03-28T20:31:45 CAT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="FAIL" signature="checkOutFlow()[pri:9, instance:ReactJsSanityTest.TC07_FurnitureCollectFromStoreTest@6e4784bc]" name="checkOutFlow" duration-ms="154236" started-at="2021-03-28T20:31:45 CAT" finished-at="2021-03-28T20:34:19 CAT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Redirecting to wrong url Test Failed expected [https://mytfgworld.uat.tfgapps.co.za/] but found [https://mytfg.tfgtst.co.za/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Redirecting to wrong url Test Failed expected [https://mytfgworld.uat.tfgapps.co.za/] but found [https://mytfg.tfgtst.co.za/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at ReactJsSanityTest.TC07_FurnitureCollectFromStoreTest.checkOutFlow(TC07_FurnitureCollectFromStoreTest.java:261)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOutFlow -->
      </class> <!-- ReactJsSanityTest.TC07_FurnitureCollectFromStoreTest -->
      <class name="ReactJsSanityTest.TC03_OurBestOffersForYouShowMeAllTest">
        <test-method status="FAIL" signature="launchReactUat()[pri:3, instance:ReactJsSanityTest.TC03_OurBestOffersForYouShowMeAllTest@34b7ac2f]" name="launchReactUat" duration-ms="40779" started-at="2021-03-28T20:34:19 CAT" finished-at="2021-03-28T20:35:00 CAT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[images not Loading properly or Broken!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: images not Loading properly or Broken!
at org.testng.Assert.fail(Assert.java:97)
at ReactJsSanityTest.TC03_OurBestOffersForYouShowMeAllTest.launchReactUat(TC03_OurBestOffersForYouShowMeAllTest.java:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchReactUat -->
      </class> <!-- ReactJsSanityTest.TC03_OurBestOffersForYouShowMeAllTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
